### ISSUE TITLE
jQuery bracket research

### ISSUE THREAD

**Issue by gmhurley** [TIY-Bracket/bracket_api#4]

**Comment by gmhurley** [comment]
- Will this work for us?
- What is the format for data input?
- Where is the best place for this to live? Inside Django or outside?
- Can we get a sample up with this?

**** HOW IS DATA FED INTO THIS THING***

**Comment by TylerKotkin** [comment]
tabling jQuery for now

**Comment by TylerKotkin** [comment]
tabling jQuery research for now.
